name: feature-release CI
run-name: ${{ github.actor }} is integrating feature-01
on: 
  push:
    branchs: 
      - b*.*.*
jobs:
  ci-feature-01:
    runs-on: ubuntu-latest
    env:
      BEANCH_NAME:  ${{github.ref}}
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ github.token }}
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Setup environment veriable
        run: |
          VERSTION="${REF_NAME#  refs/heads/b}"
          echo "VERSTION"=${VERSTION} >> $GITHUB_ENV
          echo "BRANCH_NAME=b${VERSTION} >> $GITHUB_ENV
          echo "TAG_NAME=${VERSTION} >> $GITHUB_ENV
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile
        name: Build project
      - run: npx ng build --configuration=production --base-href="/${{ github.event.repository.name }}/"
        name: Lint project
      - run: yarn run lint
        name: Test project
      - run: yarn run test:ci
      - name: Merge to main
        run: |
          git fetch --unshallow
          git checkout main
          git merge ${{env.BRANCE_NAME}}
          git push origin main
          git tsg -a ${{env.BRANCE_NAME}} -m "my version ${{env.BRANCE_NAME}}"
          git push origin main --tags