name: Main release ci
run-name: ${{ github.actor }} is integrating feature-01
on: 
  push:
    branchs: 
      - v*.*.*
jobs:
  ci-feature-01:
    runs-on: ubuntu-latest
    env:
      BEANCH_NAME:  ${{secrets.RELEASE_TOKEN}}
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secerts.RELEASE_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Setup git user
        run: |
          git config --global user.email "${{ github.event.pusher.email }}"
          git config --global user.name "${{ github.actor }}"
      - name: Release main
        uses: action/create-release@v1
        env:
          GITHUB_TOKEN: ${{secrets.RELEASE_TOKEN}}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false


